name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync code from LeetCode
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
          destination-folder: 'leetcode'
          verbose: true
          commit-header: '[LeetCode Sync]'
